version: '3.6' #the version of the docker compose

services:
  
  client-side: #name of the service
    container_name: cliret-side # name of the container
    build: ./client/ #w here its find the docker file that tell him how to build it
    command: npm start # the commentd we wont it to run after the build
    working_dir: /usr/src/app #what is the working dir
    ports: # port forwording
      - "3000:3000"
    volumes: #allow accsess to the file system of the docker container - allow live changing between the host and the container
      - ./client/:/usr/src/app # hostPath:containerPath
  
  backend:
    container_name: backend
    build: ./server/ #w here its find the docker file that tell him how to build it
    command: npm run develop # the commentd we wont it to run after the build
    working_dir: /usr/src/app #what is the working dir
    ports: # port forwording
      - "80:80"
    volumes: #allow accsess to the file system of the docker container - allow live changing between the host and the container
      - ./server/:/usr/src/app # hostPath:containerPath
    links:
      - postgres
    environment:
      POSTGRES_URI: postgres://myUser:myPassword@postgres:5432/notesApp
  
  postgres:
    image: postgres:11
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: notesApp
      POSTGRES_HOST: postgres
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080